/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  LoginByEmailRequest,
  LoginStoreAdminRequest
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const authControllerLoginByEmail = (
    loginByEmailRequest: LoginByEmailRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginByEmailRequest, signal
    },
      options);
    }
  


export const getAuthControllerLoginByEmailMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginByEmail>>, TError,{data: LoginByEmailRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginByEmail>>, TError,{data: LoginByEmailRequest}, TContext> => {

const mutationKey = ['authControllerLoginByEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLoginByEmail>>, {data: LoginByEmailRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerLoginByEmail(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLoginByEmailMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLoginByEmail>>>
    export type AuthControllerLoginByEmailMutationBody = LoginByEmailRequest
    export type AuthControllerLoginByEmailMutationError = unknown

    export const useAuthControllerLoginByEmail = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginByEmail>>, TError,{data: LoginByEmailRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLoginByEmail>>,
        TError,
        {data: LoginByEmailRequest},
        TContext
      > => {

      const mutationOptions = getAuthControllerLoginByEmailMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const authControllerGetNewAccessToken = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/auth/refresh`, method: 'POST', signal
    },
      options);
    }
  


export const getAuthControllerGetNewAccessTokenMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGetNewAccessToken>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerGetNewAccessToken>>, TError,void, TContext> => {

const mutationKey = ['authControllerGetNewAccessToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerGetNewAccessToken>>, void> = () => {
          

          return  authControllerGetNewAccessToken(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerGetNewAccessTokenMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerGetNewAccessToken>>>
    
    export type AuthControllerGetNewAccessTokenMutationError = unknown

    export const useAuthControllerGetNewAccessToken = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGetNewAccessToken>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerGetNewAccessToken>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerGetNewAccessTokenMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const authControllerLogout = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/auth/logout`, method: 'POST', signal
    },
      options);
    }
  


export const getAuthControllerLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext> => {

const mutationKey = ['authControllerLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogout>>, void> = () => {
          

          return  authControllerLogout(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogout>>>
    
    export type AuthControllerLogoutMutationError = unknown

    export const useAuthControllerLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const authControllerLoginStoreAdmin = (
    loginStoreAdminRequest: LoginStoreAdminRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/auth/store/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginStoreAdminRequest, signal
    },
      options);
    }
  


export const getAuthControllerLoginStoreAdminMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginStoreAdmin>>, TError,{data: LoginStoreAdminRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginStoreAdmin>>, TError,{data: LoginStoreAdminRequest}, TContext> => {

const mutationKey = ['authControllerLoginStoreAdmin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLoginStoreAdmin>>, {data: LoginStoreAdminRequest}> = (props) => {
          const {data} = props ?? {};

          return  authControllerLoginStoreAdmin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLoginStoreAdminMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLoginStoreAdmin>>>
    export type AuthControllerLoginStoreAdminMutationBody = LoginStoreAdminRequest
    export type AuthControllerLoginStoreAdminMutationError = unknown

    export const useAuthControllerLoginStoreAdmin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginStoreAdmin>>, TError,{data: LoginStoreAdminRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLoginStoreAdmin>>,
        TError,
        {data: LoginStoreAdminRequest},
        TContext
      > => {

      const mutationOptions = getAuthControllerLoginStoreAdminMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const authControllerGetNewStoreAccessToken = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/auth/store/refresh`, method: 'POST', signal
    },
      options);
    }
  


export const getAuthControllerGetNewStoreAccessTokenMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGetNewStoreAccessToken>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerGetNewStoreAccessToken>>, TError,void, TContext> => {

const mutationKey = ['authControllerGetNewStoreAccessToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerGetNewStoreAccessToken>>, void> = () => {
          

          return  authControllerGetNewStoreAccessToken(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerGetNewStoreAccessTokenMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerGetNewStoreAccessToken>>>
    
    export type AuthControllerGetNewStoreAccessTokenMutationError = unknown

    export const useAuthControllerGetNewStoreAccessToken = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerGetNewStoreAccessToken>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerGetNewStoreAccessToken>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerGetNewStoreAccessTokenMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    