/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CompleteSettlementRequest,
  CompleteSettlementResponse,
  GetSettlementListResponse,
  SettlementControllerGetSettlementListParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const settlementControllerGetSettlementList = (
    params: SettlementControllerGetSettlementListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetSettlementListResponse>(
      {url: `/settlement`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getSettlementControllerGetSettlementListQueryKey = (params?: SettlementControllerGetSettlementListParams,) => {
    return [
    `/settlement`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSettlementControllerGetSettlementListQueryOptions = <TData = Awaited<ReturnType<typeof settlementControllerGetSettlementList>>, TError = unknown>(params: SettlementControllerGetSettlementListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settlementControllerGetSettlementList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSettlementControllerGetSettlementListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof settlementControllerGetSettlementList>>> = ({ signal }) => settlementControllerGetSettlementList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof settlementControllerGetSettlementList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SettlementControllerGetSettlementListQueryResult = NonNullable<Awaited<ReturnType<typeof settlementControllerGetSettlementList>>>
export type SettlementControllerGetSettlementListQueryError = unknown


export function useSettlementControllerGetSettlementList<TData = Awaited<ReturnType<typeof settlementControllerGetSettlementList>>, TError = unknown>(
 params: SettlementControllerGetSettlementListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof settlementControllerGetSettlementList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof settlementControllerGetSettlementList>>,
          TError,
          Awaited<ReturnType<typeof settlementControllerGetSettlementList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettlementControllerGetSettlementList<TData = Awaited<ReturnType<typeof settlementControllerGetSettlementList>>, TError = unknown>(
 params: SettlementControllerGetSettlementListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settlementControllerGetSettlementList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof settlementControllerGetSettlementList>>,
          TError,
          Awaited<ReturnType<typeof settlementControllerGetSettlementList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettlementControllerGetSettlementList<TData = Awaited<ReturnType<typeof settlementControllerGetSettlementList>>, TError = unknown>(
 params: SettlementControllerGetSettlementListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settlementControllerGetSettlementList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSettlementControllerGetSettlementList<TData = Awaited<ReturnType<typeof settlementControllerGetSettlementList>>, TError = unknown>(
 params: SettlementControllerGetSettlementListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settlementControllerGetSettlementList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSettlementControllerGetSettlementListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const settlementControllerCompleteSettlement = (
    completeSettlementRequest: CompleteSettlementRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<CompleteSettlementResponse>(
      {url: `/settlement/complete`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: completeSettlementRequest
    },
      options);
    }
  


export const getSettlementControllerCompleteSettlementMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settlementControllerCompleteSettlement>>, TError,{data: CompleteSettlementRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof settlementControllerCompleteSettlement>>, TError,{data: CompleteSettlementRequest}, TContext> => {

const mutationKey = ['settlementControllerCompleteSettlement'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof settlementControllerCompleteSettlement>>, {data: CompleteSettlementRequest}> = (props) => {
          const {data} = props ?? {};

          return  settlementControllerCompleteSettlement(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SettlementControllerCompleteSettlementMutationResult = NonNullable<Awaited<ReturnType<typeof settlementControllerCompleteSettlement>>>
    export type SettlementControllerCompleteSettlementMutationBody = CompleteSettlementRequest
    export type SettlementControllerCompleteSettlementMutationError = unknown

    export const useSettlementControllerCompleteSettlement = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof settlementControllerCompleteSettlement>>, TError,{data: CompleteSettlementRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof settlementControllerCompleteSettlement>>,
        TError,
        {data: CompleteSettlementRequest},
        TContext
      > => {

      const mutationOptions = getSettlementControllerCompleteSettlementMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    