/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetInquiryDetailResponse,
  GetInquiryListResponse,
  InquiryControllerGetInquiryListParams,
  RegisterInquiryRequest,
  RegisterInquiryResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const inquiryControllerGetInquiryList = (
    params: InquiryControllerGetInquiryListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetInquiryListResponse>(
      {url: `/inquiry`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getInquiryControllerGetInquiryListQueryKey = (params?: InquiryControllerGetInquiryListParams,) => {
    return [
    `/inquiry`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getInquiryControllerGetInquiryListQueryOptions = <TData = Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>, TError = unknown>(params: InquiryControllerGetInquiryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInquiryControllerGetInquiryListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>> = ({ signal }) => inquiryControllerGetInquiryList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InquiryControllerGetInquiryListQueryResult = NonNullable<Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>>
export type InquiryControllerGetInquiryListQueryError = unknown


export function useInquiryControllerGetInquiryList<TData = Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>, TError = unknown>(
 params: InquiryControllerGetInquiryListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>,
          TError,
          Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInquiryControllerGetInquiryList<TData = Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>, TError = unknown>(
 params: InquiryControllerGetInquiryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>,
          TError,
          Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInquiryControllerGetInquiryList<TData = Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>, TError = unknown>(
 params: InquiryControllerGetInquiryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useInquiryControllerGetInquiryList<TData = Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>, TError = unknown>(
 params: InquiryControllerGetInquiryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inquiryControllerGetInquiryList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInquiryControllerGetInquiryListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const inquiryControllerRegisterInquiry = (
    registerInquiryRequest: RegisterInquiryRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterInquiryResponse>(
      {url: `/inquiry`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerInquiryRequest, signal
    },
      options);
    }
  


export const getInquiryControllerRegisterInquiryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inquiryControllerRegisterInquiry>>, TError,{data: RegisterInquiryRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof inquiryControllerRegisterInquiry>>, TError,{data: RegisterInquiryRequest}, TContext> => {

const mutationKey = ['inquiryControllerRegisterInquiry'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inquiryControllerRegisterInquiry>>, {data: RegisterInquiryRequest}> = (props) => {
          const {data} = props ?? {};

          return  inquiryControllerRegisterInquiry(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InquiryControllerRegisterInquiryMutationResult = NonNullable<Awaited<ReturnType<typeof inquiryControllerRegisterInquiry>>>
    export type InquiryControllerRegisterInquiryMutationBody = RegisterInquiryRequest
    export type InquiryControllerRegisterInquiryMutationError = unknown

    export const useInquiryControllerRegisterInquiry = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inquiryControllerRegisterInquiry>>, TError,{data: RegisterInquiryRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inquiryControllerRegisterInquiry>>,
        TError,
        {data: RegisterInquiryRequest},
        TContext
      > => {

      const mutationOptions = getInquiryControllerRegisterInquiryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const inquiryControllerGetUserDetail = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetInquiryDetailResponse>(
      {url: `/inquiry/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getInquiryControllerGetUserDetailQueryKey = (id?: string,) => {
    return [
    `/inquiry/${id}`
    ] as const;
    }

    
export const getInquiryControllerGetUserDetailQueryOptions = <TData = Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInquiryControllerGetUserDetailQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>> = ({ signal }) => inquiryControllerGetUserDetail(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InquiryControllerGetUserDetailQueryResult = NonNullable<Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>>
export type InquiryControllerGetUserDetailQueryError = unknown


export function useInquiryControllerGetUserDetail<TData = Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>,
          TError,
          Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInquiryControllerGetUserDetail<TData = Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>,
          TError,
          Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInquiryControllerGetUserDetail<TData = Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useInquiryControllerGetUserDetail<TData = Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof inquiryControllerGetUserDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInquiryControllerGetUserDetailQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



