/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  RegisterInquiryRequest,
  RegisterInquiryResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const inquiryControllerRegisterInquiry = (
    registerInquiryRequest: RegisterInquiryRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterInquiryResponse>(
      {url: `/inquiry`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerInquiryRequest, signal
    },
      options);
    }
  


export const getInquiryControllerRegisterInquiryMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inquiryControllerRegisterInquiry>>, TError,{data: RegisterInquiryRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof inquiryControllerRegisterInquiry>>, TError,{data: RegisterInquiryRequest}, TContext> => {

const mutationKey = ['inquiryControllerRegisterInquiry'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof inquiryControllerRegisterInquiry>>, {data: RegisterInquiryRequest}> = (props) => {
          const {data} = props ?? {};

          return  inquiryControllerRegisterInquiry(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InquiryControllerRegisterInquiryMutationResult = NonNullable<Awaited<ReturnType<typeof inquiryControllerRegisterInquiry>>>
    export type InquiryControllerRegisterInquiryMutationBody = RegisterInquiryRequest
    export type InquiryControllerRegisterInquiryMutationError = unknown

    export const useInquiryControllerRegisterInquiry = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof inquiryControllerRegisterInquiry>>, TError,{data: RegisterInquiryRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof inquiryControllerRegisterInquiry>>,
        TError,
        {data: RegisterInquiryRequest},
        TContext
      > => {

      const mutationOptions = getInquiryControllerRegisterInquiryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    