/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UploadPastSalesByExcelFileRequest,
  UploadPastSalesByExcelFileResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const salesControllerUploadPastSalesByExcelFile = (
    uploadPastSalesByExcelFileRequest: UploadPastSalesByExcelFileRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`storeId`, uploadPastSalesByExcelFileRequest.storeId)

      return customInstance<UploadPastSalesByExcelFileResponse>(
      {url: `/sales/upload`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }
  


export const getSalesControllerUploadPastSalesByExcelFileMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof salesControllerUploadPastSalesByExcelFile>>, TError,{data: UploadPastSalesByExcelFileRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof salesControllerUploadPastSalesByExcelFile>>, TError,{data: UploadPastSalesByExcelFileRequest}, TContext> => {

const mutationKey = ['salesControllerUploadPastSalesByExcelFile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof salesControllerUploadPastSalesByExcelFile>>, {data: UploadPastSalesByExcelFileRequest}> = (props) => {
          const {data} = props ?? {};

          return  salesControllerUploadPastSalesByExcelFile(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SalesControllerUploadPastSalesByExcelFileMutationResult = NonNullable<Awaited<ReturnType<typeof salesControllerUploadPastSalesByExcelFile>>>
    export type SalesControllerUploadPastSalesByExcelFileMutationBody = UploadPastSalesByExcelFileRequest
    export type SalesControllerUploadPastSalesByExcelFileMutationError = unknown

    export const useSalesControllerUploadPastSalesByExcelFile = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof salesControllerUploadPastSalesByExcelFile>>, TError,{data: UploadPastSalesByExcelFileRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof salesControllerUploadPastSalesByExcelFile>>,
        TError,
        {data: UploadPastSalesByExcelFileRequest},
        TContext
      > => {

      const mutationOptions = getSalesControllerUploadPastSalesByExcelFileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    