/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetStoreAdminInfoResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const adminControllerGetStoreAdminInfo = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetStoreAdminInfoResponse>(
      {url: `/admin`, method: 'GET', signal
    },
      options);
    }
  



export const getAdminControllerGetStoreAdminInfoQueryKey = () => {
    return [
    `/admin`
    ] as const;
    }

    
export const getAdminControllerGetStoreAdminInfoQueryOptions = <TData = Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminControllerGetStoreAdminInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>> = ({ signal }) => adminControllerGetStoreAdminInfo(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminControllerGetStoreAdminInfoQueryResult = NonNullable<Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>>
export type AdminControllerGetStoreAdminInfoQueryError = unknown


export function useAdminControllerGetStoreAdminInfo<TData = Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetStoreAdminInfo<TData = Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>,
          TError,
          Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminControllerGetStoreAdminInfo<TData = Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAdminControllerGetStoreAdminInfo<TData = Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminControllerGetStoreAdminInfo>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminControllerGetStoreAdminInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



