/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetTicketListResponse,
  RefundTicketRequest,
  RefundTicketResponse,
  TicketControllerGetTicketListParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const ticketControllerGetTicketList = (
    params: TicketControllerGetTicketListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetTicketListResponse>(
      {url: `/ticket`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getTicketControllerGetTicketListQueryKey = (params?: TicketControllerGetTicketListParams,) => {
    return [
    `/ticket`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getTicketControllerGetTicketListQueryOptions = <TData = Awaited<ReturnType<typeof ticketControllerGetTicketList>>, TError = unknown>(params: TicketControllerGetTicketListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerGetTicketList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTicketControllerGetTicketListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof ticketControllerGetTicketList>>> = ({ signal }) => ticketControllerGetTicketList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ticketControllerGetTicketList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TicketControllerGetTicketListQueryResult = NonNullable<Awaited<ReturnType<typeof ticketControllerGetTicketList>>>
export type TicketControllerGetTicketListQueryError = unknown


export function useTicketControllerGetTicketList<TData = Awaited<ReturnType<typeof ticketControllerGetTicketList>>, TError = unknown>(
 params: TicketControllerGetTicketListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerGetTicketList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof ticketControllerGetTicketList>>,
          TError,
          Awaited<ReturnType<typeof ticketControllerGetTicketList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTicketControllerGetTicketList<TData = Awaited<ReturnType<typeof ticketControllerGetTicketList>>, TError = unknown>(
 params: TicketControllerGetTicketListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerGetTicketList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof ticketControllerGetTicketList>>,
          TError,
          Awaited<ReturnType<typeof ticketControllerGetTicketList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTicketControllerGetTicketList<TData = Awaited<ReturnType<typeof ticketControllerGetTicketList>>, TError = unknown>(
 params: TicketControllerGetTicketListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerGetTicketList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTicketControllerGetTicketList<TData = Awaited<ReturnType<typeof ticketControllerGetTicketList>>, TError = unknown>(
 params: TicketControllerGetTicketListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ticketControllerGetTicketList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTicketControllerGetTicketListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const ticketControllerRefundTicket = (
    refundTicketRequest: RefundTicketRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RefundTicketResponse>(
      {url: `/ticket/refund`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refundTicketRequest, signal
    },
      options);
    }
  


export const getTicketControllerRefundTicketMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ticketControllerRefundTicket>>, TError,{data: RefundTicketRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof ticketControllerRefundTicket>>, TError,{data: RefundTicketRequest}, TContext> => {

const mutationKey = ['ticketControllerRefundTicket'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ticketControllerRefundTicket>>, {data: RefundTicketRequest}> = (props) => {
          const {data} = props ?? {};

          return  ticketControllerRefundTicket(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TicketControllerRefundTicketMutationResult = NonNullable<Awaited<ReturnType<typeof ticketControllerRefundTicket>>>
    export type TicketControllerRefundTicketMutationBody = RefundTicketRequest
    export type TicketControllerRefundTicketMutationError = unknown

    export const useTicketControllerRefundTicket = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ticketControllerRefundTicket>>, TError,{data: RefundTicketRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof ticketControllerRefundTicket>>,
        TError,
        {data: RefundTicketRequest},
        TContext
      > => {

      const mutationOptions = getTicketControllerRefundTicketMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    