/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UpdatePastWeatherHistoriesRequest,
  UpdatePastWeatherHistoriesResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const weatherControllerUpdatePastWeatherHistories = (
    updatePastWeatherHistoriesRequest: UpdatePastWeatherHistoriesRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UpdatePastWeatherHistoriesResponse>(
      {url: `/weather`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updatePastWeatherHistoriesRequest
    },
      options);
    }
  


export const getWeatherControllerUpdatePastWeatherHistoriesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof weatherControllerUpdatePastWeatherHistories>>, TError,{data: UpdatePastWeatherHistoriesRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof weatherControllerUpdatePastWeatherHistories>>, TError,{data: UpdatePastWeatherHistoriesRequest}, TContext> => {

const mutationKey = ['weatherControllerUpdatePastWeatherHistories'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof weatherControllerUpdatePastWeatherHistories>>, {data: UpdatePastWeatherHistoriesRequest}> = (props) => {
          const {data} = props ?? {};

          return  weatherControllerUpdatePastWeatherHistories(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type WeatherControllerUpdatePastWeatherHistoriesMutationResult = NonNullable<Awaited<ReturnType<typeof weatherControllerUpdatePastWeatherHistories>>>
    export type WeatherControllerUpdatePastWeatherHistoriesMutationBody = UpdatePastWeatherHistoriesRequest
    export type WeatherControllerUpdatePastWeatherHistoriesMutationError = unknown

    export const useWeatherControllerUpdatePastWeatherHistories = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof weatherControllerUpdatePastWeatherHistories>>, TError,{data: UpdatePastWeatherHistoriesRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof weatherControllerUpdatePastWeatherHistories>>,
        TError,
        {data: UpdatePastWeatherHistoriesRequest},
        TContext
      > => {

      const mutationOptions = getWeatherControllerUpdatePastWeatherHistoriesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    