/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UsePassByCarNumberRequest,
  UsePassByCarNumberResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const passControllerUsePassByCarNumber = (
    usePassByCarNumberRequest: UsePassByCarNumberRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UsePassByCarNumberResponse>(
      {url: `/pass/car-number`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: usePassByCarNumberRequest, signal
    },
      options);
    }
  


export const getPassControllerUsePassByCarNumberMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof passControllerUsePassByCarNumber>>, TError,{data: UsePassByCarNumberRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof passControllerUsePassByCarNumber>>, TError,{data: UsePassByCarNumberRequest}, TContext> => {

const mutationKey = ['passControllerUsePassByCarNumber'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof passControllerUsePassByCarNumber>>, {data: UsePassByCarNumberRequest}> = (props) => {
          const {data} = props ?? {};

          return  passControllerUsePassByCarNumber(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PassControllerUsePassByCarNumberMutationResult = NonNullable<Awaited<ReturnType<typeof passControllerUsePassByCarNumber>>>
    export type PassControllerUsePassByCarNumberMutationBody = UsePassByCarNumberRequest
    export type PassControllerUsePassByCarNumberMutationError = unknown

    export const usePassControllerUsePassByCarNumber = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof passControllerUsePassByCarNumber>>, TError,{data: UsePassByCarNumberRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof passControllerUsePassByCarNumber>>,
        TError,
        {data: UsePassByCarNumberRequest},
        TContext
      > => {

      const mutationOptions = getPassControllerUsePassByCarNumberMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    