/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetPurchaseDetailByProductIdResponse,
  PurchaseControllerGetPurchaseDetailByProductIdParams,
  RefundProductRequest,
  RefundProductResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const purchaseControllerGetPurchaseDetailByProductId = (
    params: PurchaseControllerGetPurchaseDetailByProductIdParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetPurchaseDetailByProductIdResponse>(
      {url: `/purchase/product`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getPurchaseControllerGetPurchaseDetailByProductIdQueryKey = (params?: PurchaseControllerGetPurchaseDetailByProductIdParams,) => {
    return [
    `/purchase/product`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getPurchaseControllerGetPurchaseDetailByProductIdQueryOptions = <TData = Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>, TError = unknown>(params: PurchaseControllerGetPurchaseDetailByProductIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPurchaseControllerGetPurchaseDetailByProductIdQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>> = ({ signal }) => purchaseControllerGetPurchaseDetailByProductId(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PurchaseControllerGetPurchaseDetailByProductIdQueryResult = NonNullable<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>>
export type PurchaseControllerGetPurchaseDetailByProductIdQueryError = unknown


export function usePurchaseControllerGetPurchaseDetailByProductId<TData = Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>, TError = unknown>(
 params: PurchaseControllerGetPurchaseDetailByProductIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>,
          TError,
          Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePurchaseControllerGetPurchaseDetailByProductId<TData = Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>, TError = unknown>(
 params: PurchaseControllerGetPurchaseDetailByProductIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>,
          TError,
          Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePurchaseControllerGetPurchaseDetailByProductId<TData = Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>, TError = unknown>(
 params: PurchaseControllerGetPurchaseDetailByProductIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePurchaseControllerGetPurchaseDetailByProductId<TData = Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>, TError = unknown>(
 params: PurchaseControllerGetPurchaseDetailByProductIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof purchaseControllerGetPurchaseDetailByProductId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPurchaseControllerGetPurchaseDetailByProductIdQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const purchaseControllerRefundProduct = (
    refundProductRequest: RefundProductRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RefundProductResponse>(
      {url: `/purchase/refund`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refundProductRequest, signal
    },
      options);
    }
  


export const getPurchaseControllerRefundProductMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseControllerRefundProduct>>, TError,{data: RefundProductRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof purchaseControllerRefundProduct>>, TError,{data: RefundProductRequest}, TContext> => {

const mutationKey = ['purchaseControllerRefundProduct'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof purchaseControllerRefundProduct>>, {data: RefundProductRequest}> = (props) => {
          const {data} = props ?? {};

          return  purchaseControllerRefundProduct(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PurchaseControllerRefundProductMutationResult = NonNullable<Awaited<ReturnType<typeof purchaseControllerRefundProduct>>>
    export type PurchaseControllerRefundProductMutationBody = RefundProductRequest
    export type PurchaseControllerRefundProductMutationError = unknown

    export const usePurchaseControllerRefundProduct = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof purchaseControllerRefundProduct>>, TError,{data: RefundProductRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof purchaseControllerRefundProduct>>,
        TError,
        {data: RefundProductRequest},
        TContext
      > => {

      const mutationOptions = getPurchaseControllerRefundProductMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    