/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ExportSalesStatRequest,
  ExportUserStatRequest,
  GetSalesStatResponse,
  GetSummaryStatResponse,
  GetUserStatResponse,
  StatControllerGetSalesStatParams,
  StatControllerGetUserStatParams
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const statControllerGetSummaryStat = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetSummaryStatResponse>(
      {url: `/stat/summary`, method: 'GET', signal
    },
      options);
    }
  



export const getStatControllerGetSummaryStatQueryKey = () => {
    return [
    `/stat/summary`
    ] as const;
    }

    
export const getStatControllerGetSummaryStatQueryOptions = <TData = Awaited<ReturnType<typeof statControllerGetSummaryStat>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statControllerGetSummaryStat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatControllerGetSummaryStatQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof statControllerGetSummaryStat>>> = ({ signal }) => statControllerGetSummaryStat(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statControllerGetSummaryStat>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StatControllerGetSummaryStatQueryResult = NonNullable<Awaited<ReturnType<typeof statControllerGetSummaryStat>>>
export type StatControllerGetSummaryStatQueryError = unknown


export function useStatControllerGetSummaryStat<TData = Awaited<ReturnType<typeof statControllerGetSummaryStat>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof statControllerGetSummaryStat>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof statControllerGetSummaryStat>>,
          TError,
          Awaited<ReturnType<typeof statControllerGetSummaryStat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStatControllerGetSummaryStat<TData = Awaited<ReturnType<typeof statControllerGetSummaryStat>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statControllerGetSummaryStat>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof statControllerGetSummaryStat>>,
          TError,
          Awaited<ReturnType<typeof statControllerGetSummaryStat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStatControllerGetSummaryStat<TData = Awaited<ReturnType<typeof statControllerGetSummaryStat>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statControllerGetSummaryStat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStatControllerGetSummaryStat<TData = Awaited<ReturnType<typeof statControllerGetSummaryStat>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statControllerGetSummaryStat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStatControllerGetSummaryStatQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const statControllerGetUserStat = (
    params: StatControllerGetUserStatParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetUserStatResponse>(
      {url: `/stat/user`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getStatControllerGetUserStatQueryKey = (params?: StatControllerGetUserStatParams,) => {
    return [
    `/stat/user`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getStatControllerGetUserStatQueryOptions = <TData = Awaited<ReturnType<typeof statControllerGetUserStat>>, TError = unknown>(params: StatControllerGetUserStatParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statControllerGetUserStat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatControllerGetUserStatQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof statControllerGetUserStat>>> = ({ signal }) => statControllerGetUserStat(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statControllerGetUserStat>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StatControllerGetUserStatQueryResult = NonNullable<Awaited<ReturnType<typeof statControllerGetUserStat>>>
export type StatControllerGetUserStatQueryError = unknown


export function useStatControllerGetUserStat<TData = Awaited<ReturnType<typeof statControllerGetUserStat>>, TError = unknown>(
 params: StatControllerGetUserStatParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof statControllerGetUserStat>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof statControllerGetUserStat>>,
          TError,
          Awaited<ReturnType<typeof statControllerGetUserStat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStatControllerGetUserStat<TData = Awaited<ReturnType<typeof statControllerGetUserStat>>, TError = unknown>(
 params: StatControllerGetUserStatParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statControllerGetUserStat>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof statControllerGetUserStat>>,
          TError,
          Awaited<ReturnType<typeof statControllerGetUserStat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStatControllerGetUserStat<TData = Awaited<ReturnType<typeof statControllerGetUserStat>>, TError = unknown>(
 params: StatControllerGetUserStatParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statControllerGetUserStat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStatControllerGetUserStat<TData = Awaited<ReturnType<typeof statControllerGetUserStat>>, TError = unknown>(
 params: StatControllerGetUserStatParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statControllerGetUserStat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStatControllerGetUserStatQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const statControllerExportUserStat = (
    exportUserStatRequest: ExportUserStatRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/stat/user/export`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: exportUserStatRequest, signal
    },
      options);
    }
  


export const getStatControllerExportUserStatMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statControllerExportUserStat>>, TError,{data: ExportUserStatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof statControllerExportUserStat>>, TError,{data: ExportUserStatRequest}, TContext> => {

const mutationKey = ['statControllerExportUserStat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof statControllerExportUserStat>>, {data: ExportUserStatRequest}> = (props) => {
          const {data} = props ?? {};

          return  statControllerExportUserStat(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StatControllerExportUserStatMutationResult = NonNullable<Awaited<ReturnType<typeof statControllerExportUserStat>>>
    export type StatControllerExportUserStatMutationBody = ExportUserStatRequest
    export type StatControllerExportUserStatMutationError = unknown

    export const useStatControllerExportUserStat = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statControllerExportUserStat>>, TError,{data: ExportUserStatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof statControllerExportUserStat>>,
        TError,
        {data: ExportUserStatRequest},
        TContext
      > => {

      const mutationOptions = getStatControllerExportUserStatMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const statControllerGetSalesStat = (
    params: StatControllerGetSalesStatParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetSalesStatResponse>(
      {url: `/stat/sales`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getStatControllerGetSalesStatQueryKey = (params?: StatControllerGetSalesStatParams,) => {
    return [
    `/stat/sales`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getStatControllerGetSalesStatQueryOptions = <TData = Awaited<ReturnType<typeof statControllerGetSalesStat>>, TError = unknown>(params: StatControllerGetSalesStatParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statControllerGetSalesStat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStatControllerGetSalesStatQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof statControllerGetSalesStat>>> = ({ signal }) => statControllerGetSalesStat(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof statControllerGetSalesStat>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StatControllerGetSalesStatQueryResult = NonNullable<Awaited<ReturnType<typeof statControllerGetSalesStat>>>
export type StatControllerGetSalesStatQueryError = unknown


export function useStatControllerGetSalesStat<TData = Awaited<ReturnType<typeof statControllerGetSalesStat>>, TError = unknown>(
 params: StatControllerGetSalesStatParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof statControllerGetSalesStat>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof statControllerGetSalesStat>>,
          TError,
          Awaited<ReturnType<typeof statControllerGetSalesStat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStatControllerGetSalesStat<TData = Awaited<ReturnType<typeof statControllerGetSalesStat>>, TError = unknown>(
 params: StatControllerGetSalesStatParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statControllerGetSalesStat>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof statControllerGetSalesStat>>,
          TError,
          Awaited<ReturnType<typeof statControllerGetSalesStat>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStatControllerGetSalesStat<TData = Awaited<ReturnType<typeof statControllerGetSalesStat>>, TError = unknown>(
 params: StatControllerGetSalesStatParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statControllerGetSalesStat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useStatControllerGetSalesStat<TData = Awaited<ReturnType<typeof statControllerGetSalesStat>>, TError = unknown>(
 params: StatControllerGetSalesStatParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof statControllerGetSalesStat>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStatControllerGetSalesStatQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const statControllerExportSalesStat = (
    exportSalesStatRequest: ExportSalesStatRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/stat/sales/export`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: exportSalesStatRequest, signal
    },
      options);
    }
  


export const getStatControllerExportSalesStatMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statControllerExportSalesStat>>, TError,{data: ExportSalesStatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof statControllerExportSalesStat>>, TError,{data: ExportSalesStatRequest}, TContext> => {

const mutationKey = ['statControllerExportSalesStat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof statControllerExportSalesStat>>, {data: ExportSalesStatRequest}> = (props) => {
          const {data} = props ?? {};

          return  statControllerExportSalesStat(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StatControllerExportSalesStatMutationResult = NonNullable<Awaited<ReturnType<typeof statControllerExportSalesStat>>>
    export type StatControllerExportSalesStatMutationBody = ExportSalesStatRequest
    export type StatControllerExportSalesStatMutationError = unknown

    export const useStatControllerExportSalesStat = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof statControllerExportSalesStat>>, TError,{data: ExportSalesStatRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof statControllerExportSalesStat>>,
        TError,
        {data: ExportSalesStatRequest},
        TContext
      > => {

      const mutationOptions = getStatControllerExportSalesStatMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    