/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CouponControllerGetCouponInfoListParams,
  CouponControllerGetCouponListParams,
  DeleteCouponInfoRequest,
  DeleteCouponInfoResponse,
  GetCouponInfoDetailResponse,
  GetCouponInfoListResponse,
  GetCouponListResponse,
  RegisterCouponInfoRequest,
  RegisterCouponInfoResponse,
  UpdateCouponInfoRequest,
  UpdateCouponInfoResponse
} from '.././models';

import { customInstance } from '../../libs/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const couponControllerGetCouponList = (
    params: CouponControllerGetCouponListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetCouponListResponse>(
      {url: `/coupon`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getCouponControllerGetCouponListQueryKey = (params?: CouponControllerGetCouponListParams,) => {
    return [
    `/coupon`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCouponControllerGetCouponListQueryOptions = <TData = Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError = unknown>(params: CouponControllerGetCouponListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCouponControllerGetCouponListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof couponControllerGetCouponList>>> = ({ signal }) => couponControllerGetCouponList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CouponControllerGetCouponListQueryResult = NonNullable<Awaited<ReturnType<typeof couponControllerGetCouponList>>>
export type CouponControllerGetCouponListQueryError = unknown


export function useCouponControllerGetCouponList<TData = Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError = unknown>(
 params: CouponControllerGetCouponListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof couponControllerGetCouponList>>,
          TError,
          Awaited<ReturnType<typeof couponControllerGetCouponList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCouponControllerGetCouponList<TData = Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError = unknown>(
 params: CouponControllerGetCouponListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof couponControllerGetCouponList>>,
          TError,
          Awaited<ReturnType<typeof couponControllerGetCouponList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCouponControllerGetCouponList<TData = Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError = unknown>(
 params: CouponControllerGetCouponListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCouponControllerGetCouponList<TData = Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError = unknown>(
 params: CouponControllerGetCouponListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCouponControllerGetCouponListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const couponControllerGetCouponInfoList = (
    params: CouponControllerGetCouponInfoListParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetCouponInfoListResponse>(
      {url: `/coupon/info`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getCouponControllerGetCouponInfoListQueryKey = (params?: CouponControllerGetCouponInfoListParams,) => {
    return [
    `/coupon/info`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCouponControllerGetCouponInfoListQueryOptions = <TData = Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>, TError = unknown>(params: CouponControllerGetCouponInfoListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCouponControllerGetCouponInfoListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>> = ({ signal }) => couponControllerGetCouponInfoList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CouponControllerGetCouponInfoListQueryResult = NonNullable<Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>>
export type CouponControllerGetCouponInfoListQueryError = unknown


export function useCouponControllerGetCouponInfoList<TData = Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>, TError = unknown>(
 params: CouponControllerGetCouponInfoListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>,
          TError,
          Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCouponControllerGetCouponInfoList<TData = Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>, TError = unknown>(
 params: CouponControllerGetCouponInfoListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>,
          TError,
          Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCouponControllerGetCouponInfoList<TData = Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>, TError = unknown>(
 params: CouponControllerGetCouponInfoListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCouponControllerGetCouponInfoList<TData = Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>, TError = unknown>(
 params: CouponControllerGetCouponInfoListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponInfoList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCouponControllerGetCouponInfoListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const couponControllerRegisterCouponInfo = (
    registerCouponInfoRequest: RegisterCouponInfoRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<RegisterCouponInfoResponse>(
      {url: `/coupon/info`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerCouponInfoRequest, signal
    },
      options);
    }
  


export const getCouponControllerRegisterCouponInfoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof couponControllerRegisterCouponInfo>>, TError,{data: RegisterCouponInfoRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof couponControllerRegisterCouponInfo>>, TError,{data: RegisterCouponInfoRequest}, TContext> => {

const mutationKey = ['couponControllerRegisterCouponInfo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof couponControllerRegisterCouponInfo>>, {data: RegisterCouponInfoRequest}> = (props) => {
          const {data} = props ?? {};

          return  couponControllerRegisterCouponInfo(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CouponControllerRegisterCouponInfoMutationResult = NonNullable<Awaited<ReturnType<typeof couponControllerRegisterCouponInfo>>>
    export type CouponControllerRegisterCouponInfoMutationBody = RegisterCouponInfoRequest
    export type CouponControllerRegisterCouponInfoMutationError = unknown

    export const useCouponControllerRegisterCouponInfo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof couponControllerRegisterCouponInfo>>, TError,{data: RegisterCouponInfoRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof couponControllerRegisterCouponInfo>>,
        TError,
        {data: RegisterCouponInfoRequest},
        TContext
      > => {

      const mutationOptions = getCouponControllerRegisterCouponInfoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const couponControllerUpdateCouponInfo = (
    updateCouponInfoRequest: UpdateCouponInfoRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UpdateCouponInfoResponse>(
      {url: `/coupon/info`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateCouponInfoRequest
    },
      options);
    }
  


export const getCouponControllerUpdateCouponInfoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof couponControllerUpdateCouponInfo>>, TError,{data: UpdateCouponInfoRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof couponControllerUpdateCouponInfo>>, TError,{data: UpdateCouponInfoRequest}, TContext> => {

const mutationKey = ['couponControllerUpdateCouponInfo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof couponControllerUpdateCouponInfo>>, {data: UpdateCouponInfoRequest}> = (props) => {
          const {data} = props ?? {};

          return  couponControllerUpdateCouponInfo(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CouponControllerUpdateCouponInfoMutationResult = NonNullable<Awaited<ReturnType<typeof couponControllerUpdateCouponInfo>>>
    export type CouponControllerUpdateCouponInfoMutationBody = UpdateCouponInfoRequest
    export type CouponControllerUpdateCouponInfoMutationError = unknown

    export const useCouponControllerUpdateCouponInfo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof couponControllerUpdateCouponInfo>>, TError,{data: UpdateCouponInfoRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof couponControllerUpdateCouponInfo>>,
        TError,
        {data: UpdateCouponInfoRequest},
        TContext
      > => {

      const mutationOptions = getCouponControllerUpdateCouponInfoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const couponControllerDeleteCouponInfo = (
    deleteCouponInfoRequest: DeleteCouponInfoRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeleteCouponInfoResponse>(
      {url: `/coupon/info`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: deleteCouponInfoRequest
    },
      options);
    }
  


export const getCouponControllerDeleteCouponInfoMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof couponControllerDeleteCouponInfo>>, TError,{data: DeleteCouponInfoRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof couponControllerDeleteCouponInfo>>, TError,{data: DeleteCouponInfoRequest}, TContext> => {

const mutationKey = ['couponControllerDeleteCouponInfo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof couponControllerDeleteCouponInfo>>, {data: DeleteCouponInfoRequest}> = (props) => {
          const {data} = props ?? {};

          return  couponControllerDeleteCouponInfo(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CouponControllerDeleteCouponInfoMutationResult = NonNullable<Awaited<ReturnType<typeof couponControllerDeleteCouponInfo>>>
    export type CouponControllerDeleteCouponInfoMutationBody = DeleteCouponInfoRequest
    export type CouponControllerDeleteCouponInfoMutationError = unknown

    export const useCouponControllerDeleteCouponInfo = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof couponControllerDeleteCouponInfo>>, TError,{data: DeleteCouponInfoRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof couponControllerDeleteCouponInfo>>,
        TError,
        {data: DeleteCouponInfoRequest},
        TContext
      > => {

      const mutationOptions = getCouponControllerDeleteCouponInfoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const couponControllerGetCouponInfoDetail = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetCouponInfoDetailResponse>(
      {url: `/coupon/info/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getCouponControllerGetCouponInfoDetailQueryKey = (id?: string,) => {
    return [
    `/coupon/info/${id}`
    ] as const;
    }

    
export const getCouponControllerGetCouponInfoDetailQueryOptions = <TData = Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCouponControllerGetCouponInfoDetailQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>> = ({ signal }) => couponControllerGetCouponInfoDetail(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CouponControllerGetCouponInfoDetailQueryResult = NonNullable<Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>>
export type CouponControllerGetCouponInfoDetailQueryError = unknown


export function useCouponControllerGetCouponInfoDetail<TData = Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>,
          TError,
          Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCouponControllerGetCouponInfoDetail<TData = Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>,
          TError,
          Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCouponControllerGetCouponInfoDetail<TData = Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCouponControllerGetCouponInfoDetail<TData = Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof couponControllerGetCouponInfoDetail>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCouponControllerGetCouponInfoDetailQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



