/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export type CouponControllerGetCouponInfoListParams = {
/**
 * 쿠폰명
 */
name?: string;
/**
 * 쿠폰 종류
 */
type?: string;
/**
 * 이용권 종류
 * @nullable
 */
passType?: string | null;
/**
 * 서비스 종류
 * @nullable
 */
serviceType?: string | null;
/**
 * 시작일
 */
startDate?: string;
/**
 * 종료일
 */
endDate?: string;
/**
 * 정렬 기준
 */
sortBy?: string;
/**
 * 정렬 순서
 */
sortOrder?: string;
/**
 * 가져올 데이터 수
 */
take: number;
/**
 * 건너뛸 데이터 수
 */
skip: number;
};
