/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export type CouponControllerGetCouponListParams = {
/**
 * 회원 ID
 */
userId?: string;
/**
 * 쿠폰 이름
 */
name?: string;
/**
 * 쿠폰 종류
 */
type?: string;
/**
 * 이용권 종류
 * @nullable
 */
passType?: string | null;
/**
 * 서비스 종류
 * @nullable
 */
serviceType?: string | null;
/**
 * 회원 이름
 */
userName?: string;
/**
 * 회원 전화번호
 */
phoneNumber?: string;
/**
 * 사용 여부
 */
isUsed?: boolean;
/**
 * 발급일
 */
createdAt?: string;
/**
 * 만료일
 */
expiredAt?: string;
/**
 * 사용일
 */
usedAt?: string;
/**
 * 정렬 기준
 */
sortBy?: string;
/**
 * 정렬 순서
 */
sortOrder?: string;
/**
 * 가져올 데이터 수
 */
take: number;
/**
 * 건너뛸 데이터 수
 */
skip: number;
};
