/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { CouponInfoDetailItem } from './couponInfoDetailItem';

export interface GetCouponInfoDetailResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 등록 쿠폰 상세 정보 */
  data: CouponInfoDetailItem;
}
