/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { InquiryDetailItem } from './inquiryDetailItem';

export interface GetInquiryDetailResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 문의 상세 정보 */
  data: InquiryDetailItem;
}
