/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { IssuableCouponInfoListItem } from './issuableCouponInfoListItem';
import type { PaginationMetaEntity } from './paginationMetaEntity';

export interface GetIssuableCouponInfoListResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 발급 가능 쿠폰 목록 */
  data: IssuableCouponInfoListItem[];
  /** 메타 정보 */
  meta: PaginationMetaEntity;
}
