/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { SettlementListItem } from './settlementListItem';

export interface GetSettlementListResponse {
  /** 결과 여부 */
  ok: boolean;
  /** 정산 내역 목록 */
  data: SettlementListItem[];
}
