/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface InquiryListItem {
  /** ID */
  id: string;
  /** 문의 종류 */
  type: string;
  /** 회원명 */
  userName: string;
  /** 회원 전화번호 */
  phoneNumber: string;
  /**
   * 회원 이메일
   * @nullable
   */
  email?: string | null;
  /** 내용 */
  content: string;
  /** 문의일 */
  createdAt: string;
  /**
   * 답변일
   * @nullable
   */
  answeredAt?: string | null;
  /** 답변 여부 */
  isAnswered: boolean;
}
