/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export type InquiryControllerGetInquiryListParams = {
/**
 * 문의 제목
 */
title?: string;
/**
 * 문의 내용
 */
content?: string;
/**
 * 이름
 */
userName?: string;
/**
 * 전화번호
 */
phoneNumber?: string;
/**
 * 이메일
 */
email?: string;
/**
 * 가입일
 */
createdAt?: string;
/**
 * 정렬 기준
 */
sortBy?: string;
/**
 * 정렬 순서
 */
sortOrder?: string;
/**
 * 가져올 데이터 수
 */
take: number;
/**
 * 건너뛸 데이터 수
 */
skip: number;
};
