/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface IssueCouponToUsersRequest {
  /** ID */
  id: string;
  /** 전화번호 목록 */
  phoneNumbers?: string[];
}
