/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface IssueCouponToUsersResult {
  /** 발급완료 쿠폰 수량 */
  successCount: number;
  /** 발급실패 쿠폰 수량 */
  errorCount: number;
}
