/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface RegisterInquiryRequest {
  /** 회원명 */
  userName: string;
  /** 회원 전화번호 */
  phoneNumber: string;
  /** 회원 이메일 */
  email: string;
  /** 내용 */
  content: string;
}
