/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface SendMarketingMessageRequest {
  /** 제목 */
  title: string;
  /** 메세지 */
  message: string;
  /** 전화번호 목록 */
  phoneNumbers?: string[];
}
