/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export type SettlementControllerGetSettlementListParams = {
/**
 * 기간(월)
 */
period: string;
/**
 * 매장명
 */
storeName?: string;
};
