/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export type StoreControllerGetStoreListParams = {
/**
 * 회원 이름
 */
name?: string;
/**
 * 전화번호
 */
phoneNumber?: string;
/**
 * 주소
 */
address?: string;
/**
 * 서비스 종류
 */
serviceType?: string;
/**
 * 가입일
 */
createdAt?: string;
/**
 * 정렬 기준
 */
sortBy?: string;
/**
 * 정렬 순서
 */
sortOrder?: string;
/**
 * 가져올 데이터 수
 */
take: number;
/**
 * 건너뛸 데이터 수
 */
skip: number;
};
