/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionSnapshotUserItem } from './subscriptionSnapshotUserItem';
import type { SubscriptionSnapshotStoreItem } from './subscriptionSnapshotStoreItem';

export interface SubscriptionSubscriptionItem {
  /** ID */
  id: string;
  /** 일회권 상태 */
  status: string;
  /** 구독 갱신 횟수 */
  renewalCount: number;
  /** 자동결제 날짜 */
  billingDate: number;
  /** 회원 정보 */
  user: SubscriptionSnapshotUserItem;
  /** 매장 정보 */
  store: SubscriptionSnapshotStoreItem;
}
