/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */
import type { UpdateStoreRequestPassPrice } from './updateStoreRequestPassPrice';
import type { UpdateStoreRequestOfflinePrice } from './updateStoreRequestOfflinePrice';
import type { UpdateStoreRequestReceiptDiscount } from './updateStoreRequestReceiptDiscount';
import type { UpdateStoreRequestBusinessHours } from './updateStoreRequestBusinessHours';
import type { UpdateServiceOptionDto } from './updateServiceOptionDto';

export interface UpdateStoreRequest {
  /** ID */
  id: string;
  /** 이름 */
  name: string;
  /** 전화번호 */
  phoneNumber: string;
  /** 주소 */
  address: string;
  /** 위도 */
  lat: number;
  /** 경도 */
  lng: number;
  /** 매장 종류 */
  storeType: string;
  /**
   * 대표 이미지
   * @nullable
   */
  mainImage?: string | null;
  /**
   * 태그
   * @nullable
   */
  tags?: string | null;
  /**
   * 매장 공지
   * @nullable
   */
  notice?: string | null;
  /**
   * 매장 소개
   * @nullable
   */
  description?: string | null;
  /**
   * 유의사항
   * @nullable
   */
  policy?: string | null;
  /**
   * 스탠다드 구독권 최대 사용 횟수
   * @nullable
   */
  standardMaxUsage?: number | null;
  /**
   * 휴무일
   * @nullable
   */
  holidays?: string | null;
  /**
   * 휴게 시간
   * @nullable
   */
  breakTime?: string | null;
  /** 대표 이름 */
  ceoName: string;
  /** 대표 전화번호 */
  ceoPhoneNumber: string;
  /** 숨김 여부 */
  isHidden: boolean;
  /**
   * 직영 ID
   * @nullable
   */
  storeGroupId?: string | null;
  /** 이용권 가격 */
  passPrice?: UpdateStoreRequestPassPrice;
  /** 현장권 가격 */
  offlinePrice?: UpdateStoreRequestOfflinePrice;
  /** 주유 할인 가격 */
  receiptDiscount?: UpdateStoreRequestReceiptDiscount;
  /** 영업 시간 */
  businessHours?: UpdateStoreRequestBusinessHours;
  /** 서비스 옵션 목록 */
  serviceOptions?: UpdateServiceOptionDto[];
}
