/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Allta Admin
 * Allta Admin 서버 문서입니다.
 * OpenAPI spec version: 1.0
 */

export interface UserStatItem {
  /** 날짜 */
  date: string;
  /** 신규 회원 수 */
  newUsers: number;
  /** 탈퇴 회원 수 */
  deletedUsers: number;
  /** 누적 회원 수 */
  totalUsers: number;
}
